services:
  - type: web
    name: private-telegram-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: SERVER_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
